# tools/loc/fit-budget.ps1
#
# Purpose: write the table the Translate window reads to warn a translator while they
#          type that a string has to fit a narrow control. One row per localized XAML
#          string drawn in a fixed width, holding the room left for text after the
#          control's own border, padding and, for a checkbox, its box. Pixels rather
#          than characters, because "Iiii" and "MMMM" are both four.
#          The scan is Get-LocFitSites in _common.ps1, the same one validate.ps1
#          measures translations with, so the table and the check cannot disagree.
# Usage:   .\fit-budget.ps1 [-Check]
#          Run it after adding or changing a fixed Width on a localized control.
#          -Check writes nothing and exits 1 when the generated file is stale, which
#          is what validate.ps1 reports.
# Runs under Windows PowerShell 5.1.

param([switch]$Check)

Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'
. (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) '_common.ps1')

$plugin = Join-Path $LocRepoRoot 'src\TrueforceForAll.Plugin'
$target = Join-Path $plugin 'Localization\LocFitBudget.cs'
$inv = [System.Globalization.CultureInfo]::InvariantCulture

$sites = Get-LocFitSites $plugin $LocRepoRoot

# The tightest spot governs: one key can be a narrow column header in one place and a
# roomy row in another, and the translator writes one string for both.
$rooms = New-Object 'System.Collections.Generic.SortedDictionary[string,double]' ([System.StringComparer]::Ordinal)
foreach ($s in $sites) {
    if ($rooms.ContainsKey($s.Key)) {
        if ($s.Room -lt $rooms[$s.Key]) { $rooms[$s.Key] = $s.Room }
    } else {
        $rooms[$s.Key] = $s.Room
    }
}

$lines = @()
foreach ($k in $rooms.Keys) {
    $lines += ('            { "' + $k + '", ' + $rooms[$k].ToString('0.#', $inv) + ' },')
}
$entries = ($lines -join "`n")
$fontSize = $LocFitFontSize.ToString('0.0', $inv)

$body = @"
// <auto-generated>
//   tools/loc/fit-budget.ps1 writes this file. Do not edit it by hand: validate.ps1
//   works the numbers out again and fails when they disagree with what is here.
// </auto-generated>
//
// How much room each localized string has when it is drawn in a control with a fixed
// width, in device-independent pixels at FontSize. The Translate window measures what
// a translator types against this, so a string that would be cut off says so while it
// is being written rather than on someone's wheel.
//
// A key absent here has no constraint, which is almost all of them: a fixed Width is
// MinWidth wherever the control could grow, and a control that can grow needs no
// budget. That is also why this is a generated table rather than a number written by
// hand per key. The constraint belongs to the place the string is drawn, not to the
// string, and a character count does not predict a pixel.
using System.Collections.Generic;

namespace TrueforceForAll.Plugin.Localization
{
    internal static class LocFitBudget
    {
        /// <summary>The size the settings panel draws at, and so the size these
        /// numbers were measured at. A caller has to measure at the same size.</summary>
        public const double FontSize = $fontSize;

        /// <summary>Key to the pixels left for its text. The tightest site wins when
        /// a key is drawn in more than one place.</summary>
        private static readonly Dictionary<string, double> Rooms = new Dictionary<string, double>
        {
$entries
        };

        /// <summary>Room for this key's text, or 0 when nothing constrains it.</summary>
        public static double Room(string key)
        {
            double room;
            if (key != null && Rooms.TryGetValue(key, out room)) return room;
            return 0.0;
        }

        /// <summary>How many keys are constrained, for the window's own status
        /// line.</summary>
        public static int Count { get { return Rooms.Count; } }
    }
}
"@

if ($Check) {
    if (-not (Test-Path -LiteralPath $target)) {
        Write-Host ('STALE: {0} does not exist. Run tools\loc\fit-budget.ps1.' -f (Get-LocRelativePath $target $LocRepoRoot))
        exit 1
    }
    $have = (Read-LocTextFile $target).Text
    if ($have -ne $body) {
        Write-Host ('STALE: {0} does not match the XAML. Run tools\loc\fit-budget.ps1.' -f (Get-LocRelativePath $target $LocRepoRoot))
        exit 1
    }
    Write-Host ('LocFitBudget.cs is current: {0} constrained key(s) from {1} site(s).' -f $rooms.Count, $sites.Count)
    exit 0
}

Write-LocTextFile $target $body $false
Write-Host ('Wrote {0}: {1} constrained key(s) from {2} site(s), measured at {3}px.' -f `
    (Get-LocRelativePath $target $LocRepoRoot), $rooms.Count, $sites.Count, $fontSize)
exit 0
