# tools/loc/push-english.ps1
#
# Purpose: push Languages\en.json to the translation service, which is what lets the
#          server check a submission's key, its English hash, its placeholders and its
#          length. Without this the service holds no English and every submission is
#          refused with "This key is not in the English the server holds".
#          The server keeps every English a key has ever had, so a push is also what
#          makes a mixed-version fleet safe: a row names the English it translated by
#          hash, and an install applies it only when that hash matches the English the
#          install itself displays.
# Usage:   .\push-english.ps1 [-DryRun] [-Version X.Y.Z] [-Ref <sha>]
#          Applies through "supabase db query --linked", the same mechanism the rest of
#          this repo's schema changes use, so no service key has to live anywhere.
#          -DryRun writes the SQL and stops, which is how to read what would be sent.
#          Version defaults to src\Directory.Build.props, Ref to the short HEAD sha.
# Runs under Windows PowerShell 5.1, from a repo with the Supabase CLI linked.

param([switch]$DryRun, [string]$Version = '', [string]$Ref = '')

Set-StrictMode -Version 2
$ErrorActionPreference = 'Stop'
. (Join-Path (Split-Path -Parent $MyInvocation.MyCommand.Path) '_common.ps1')

$enPath = Join-Path $LocRepoRoot $LocEnJsonRel

# ---- the encoding preflight, before anything is sent.
# Three vectors from real en.json values. The middle one is the point: a wrong second
# hash means something on this path is encoding text as Windows-1252, and every row
# would then name an English the server does not have.
function Get-LocSha256([string]$Value) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try {
        $bytes = [System.Text.Encoding]::UTF8.GetBytes($Value)
        return -join ($sha.ComputeHash($bytes) | ForEach-Object { $_.ToString('x2') })
    } finally { $sha.Dispose() }
}
$vectors = @(
    @{ t = 'Sign in';           h = 'bfd402b2f6f3812529b55596136d3a11c51616317e3b1cd999928e2d4eae7d3f' },
    @{ t = ('Change' + [char]0x2026); h = 'a6b4705c688314f0a6e0de5886c082aab286c8fc763490d724218e7f5f53c54e' },
    @{ t = 'Signed in as {0}.'; h = '57d8ac41163a34ec577c56848983580e14ffacf51935889a9591bc9537bd698a' }
)
foreach ($v in $vectors) {
    $got = Get-LocSha256 $v.t
    if ($got -ne $v.h) {
        throw ("Hash vector failed: expected $($v.h), got $got. Something on this path is not writing UTF-8.")
    }
}
Write-Host 'Hash vectors: 3 of 3 match.'

# ---- what is being pushed, and as which version
if ($Version -eq '') {
    $props = Join-Path $LocRepoRoot 'src\Directory.Build.props'
    $m = [regex]::Match((Get-Content -LiteralPath $props -Raw), '<Version[^>]*>([^<]+)</Version>')
    if (-not $m.Success) { throw "No <Version> in $props; pass -Version." }
    $Version = $m.Groups[1].Value
}
if ($Ref -eq '') {
    $Ref = (& git -C $LocRepoRoot rev-parse --short HEAD).Trim()
    if ($LASTEXITCODE -ne 0 -or $Ref -eq '') { throw 'Could not read HEAD; pass -Ref.' }
}

$en = Read-LocJson $enPath
$rows = New-Object System.Collections.Generic.List[object]
foreach ($k in $en.Keys) {
    if ($k -eq '_meta') { continue }
    # context.area is the group the Translate window shows and the page will: the key's
    # own prefix. The rest of the context the design names (siblingNames, helpText,
    # ownToolTip) is not built, so it is absent rather than empty.
    $cut = $k.IndexOf('_')
    $area = if ($cut -gt 0) { $k.Substring(0, $cut) } else { $k }
    $rows.Add([ordered]@{ k = $k; t = [string]$en[$k]; c = [ordered]@{ area = $area } })
}
Write-Host ('en.json: {0} key(s) at version {1}, ref {2}.' -f $rows.Count, $Version, $Ref)

# Depth 4 keeps the context object intact; Compress keeps the file near 400 KB rather
# than several MB of indentation.
$json = ($rows | ConvertTo-Json -Depth 4 -Compress)
if ($json -like '*$loc$*') { throw 'en.json contains the dollar-quote tag; change the tag before sending.' }

$sqlPath = Join-Path $env:TEMP 'tf4all-push-english.sql'
$sql = @"
-- Generated by tools/loc/push-english.ps1. Not a migration: this is data.
select public.upsert_english_strings(
    '$Version',
    '$Ref',
    `$loc`$$json`$loc`$::jsonb) as receipt;
"@
Write-LocNewFile $sqlPath $sql
Write-Host ('Wrote {0} ({1:N0} bytes).' -f $sqlPath, (Get-Item -LiteralPath $sqlPath).Length)

if ($DryRun) {
    Write-Host 'Dry run: nothing sent.'
    exit 0
}

& supabase db query --linked -f $sqlPath
if ($LASTEXITCODE -ne 0) { throw 'The push failed; nothing was changed.' }
Write-Host 'Pushed. The receipt above says added, changed, retired and live.'
exit 0
