// <auto-generated>
//   tools/loc/fit-budget.ps1 writes this file. Do not edit it by hand: validate.ps1
//   works the numbers out again and fails when they disagree with what is here.
// </auto-generated>
//
// How much room each localized string has when it is drawn in a control with a fixed
// width, in device-independent pixels at FontSize. The Translate window measures what
// a translator types against this, so a string that would be cut off says so while it
// is being written rather than on someone's wheel.
//
// A key absent here has no constraint, which is almost all of them: a fixed Width is
// MinWidth wherever the control could grow, and a control that can grow needs no
// budget. That is also why this is a generated table rather than a number written by
// hand per key. The constraint belongs to the place the string is drawn, not to the
// string, and a character count does not predict a pixel.
using System.Collections.Generic;

namespace TrueforceForAll.Plugin.Localization
{
    internal static class LocFitBudget
    {
        /// <summary>The size the settings panel draws at, and so the size these
        /// numbers were measured at. A caller has to measure at the same size.</summary>
        public const double FontSize = 13.0;

        /// <summary>Key to the pixels left for its text. The tightest site wins when
        /// a key is drawn in more than one place.</summary>
        private static readonly Dictionary<string, double> Rooms = new Dictionary<string, double>
        {
            { "Account_AccountChangeEmailRowEmail", 98 },
            { "Common_Apply", 68 },
            { "Common_Cancel", 64 },
            { "Common_CarId", 100 },
            { "Common_Game", 80 },
            { "Common_PresetName", 170 },
            { "Common_Save", 64 },
            { "Common_SharedBy", 100 },
            { "Common_Source", 100 },
            { "Effects_AirborneDuckAudio", 124 },
            { "Effects_AirborneDuckCollision", 124 },
            { "Effects_AirborneDuckDrs", 124 },
            { "Effects_AirborneDuckEngine", 124 },
            { "Effects_AirborneDuckPitLimiter", 124 },
            { "Header_OfflineEditDone", 64 },
            { "PresetManager_CommunityItemCountCol_Header", 60 },
            { "PresetManager_CommunityListVote_Header", 44 },
            { "PresetManager_CommunityScopeCol_Header", 100 },
            { "PresetManager_CommunitySectionsCol_Header", 140 },
            { "PresetManager_CommunityStateCol_Header", 90 },
            { "PresetManager_CustomListDetail_Header", 200 },
            { "PresetManager_CustomListType_Header", 110 },
            { "PresetManager_DevBarValidate", 70 },
            { "PresetManager_Export", 80 },
            { "PresetManager_GameListDefaultFor_Header", 220 },
            { "PresetManager_Import", 80 },
            { "PresetManager_InstalledPacks", 120 },
            { "PresetManager_PacksCreate", 100 },
            { "PresetManager_PacksListEntries_Header", 50 },
            { "PresetManager_PacksListImported_Header", 100 },
            { "PresetManager_PacksListVersion_Header", 60 },
            { "Settings_ForzaDiscoveryAdopt", 60 },
            { "Settings_ForzaDiscoveryDismiss", 60 },
            { "Settings_RemoteDashTheme", 50 },
            { "Settings_Restore", 120 },
            { "TelemetryFfb_FxAutoTune", 80 },
            { "TelemetryFfb_FxTestStop", 50 },
            { "TelemetryFfb_FxTrace", 80 },
        };

        /// <summary>Room for this key's text, or 0 when nothing constrains it.</summary>
        public static double Room(string key)
        {
            double room;
            if (key != null && Rooms.TryGetValue(key, out room)) return room;
            return 0.0;
        }

        /// <summary>How many keys are constrained, for the window's own status
        /// line.</summary>
        public static int Count { get { return Rooms.Count; } }
    }
}